insert into public.exercises (user_id, name, category, muscle_group, equipment, tracking_type) values
  (null,'Bench Press','strength','chest','barbell','weight_reps'),
  (null,'Incline Bench Press','strength','chest','barbell','weight_reps'),
  (null,'Dumbbell Bench Press','strength','chest','dumbbell','weight_reps'),
  (null,'Chest Fly (Cable)','strength','chest','cable','weight_reps'),
  (null,'Push-up','strength','chest','bodyweight','reps'),
  (null,'Dips','strength','triceps','bodyweight','reps'),
  (null,'Overhead Press','strength','shoulders','barbell','weight_reps'),
  (null,'Dumbbell Shoulder Press','strength','shoulders','dumbbell','weight_reps'),
  (null,'Lateral Raise','strength','shoulders','dumbbell','weight_reps'),
  (null,'Face Pull','strength','shoulders','cable','weight_reps'),
  (null,'Squat','strength','quads','barbell','weight_reps'),
  (null,'Front Squat','strength','quads','barbell','weight_reps'),
  (null,'Leg Press','strength','quads','machine','weight_reps'),
  (null,'Leg Extension','strength','quads','machine','weight_reps'),
  (null,'Bulgarian Split Squat','strength','quads','dumbbell','weight_reps'),
  (null,'Walking Lunge','strength','quads','dumbbell','weight_reps'),
  (null,'Deadlift','strength','back','barbell','weight_reps'),
  (null,'Romanian Deadlift','strength','hamstrings','barbell','weight_reps'),
  (null,'Leg Curl','strength','hamstrings','machine','weight_reps'),
  (null,'Hip Thrust','strength','glutes','barbell','weight_reps'),
  (null,'Standing Calf Raise','strength','calves','machine','weight_reps'),
  (null,'Pull-up','strength','back','bodyweight','reps'),
  (null,'Chin-up','strength','back','bodyweight','reps'),
  (null,'Lat Pulldown','strength','back','cable','weight_reps'),
  (null,'Barbell Row','strength','back','barbell','weight_reps'),
  (null,'Dumbbell Row','strength','back','dumbbell','weight_reps'),
  (null,'Seated Cable Row','strength','back','cable','weight_reps'),
  (null,'Barbell Curl','strength','biceps','barbell','weight_reps'),
  (null,'Dumbbell Curl','strength','biceps','dumbbell','weight_reps'),
  (null,'Hammer Curl','strength','biceps','dumbbell','weight_reps'),
  (null,'Triceps Pushdown','strength','triceps','cable','weight_reps'),
  (null,'Skull Crusher','strength','triceps','barbell','weight_reps'),
  (null,'Overhead Triceps Extension','strength','triceps','dumbbell','weight_reps'),
  (null,'Kettlebell Swing','strength','full_body','kettlebell','weight_reps'),
  (null,'Plank','strength','core','bodyweight','duration'),
  (null,'Hanging Leg Raise','strength','core','bodyweight','reps'),
  (null,'Cable Crunch','strength','core','cable','weight_reps'),
  (null,'Running','cardio','cardio','other','distance_duration'),
  (null,'Cycling','cardio','cardio','machine','distance_duration'),
  (null,'Rowing Machine','cardio','cardio','machine','distance_duration'),
  (null,'Walking','cardio','cardio','other','distance_duration'),
  (null,'Jump Rope','cardio','cardio','other','duration'),
  (null,'Stretching','mobility','full_body','other','duration')
on conflict (lower(name)) where user_id is null do nothing;
